#!/bin/sh
file="$(ls | fzf)"
obj="$(echo "${file%.*}")"
[[ $file = *.c ]] && gcc -Wall -Wextra -Wshadow -o "$obj" "$file" && echo "Compilation succesful."; exit
[[ $file = *.cpp ]] && g++ -Wall -Wextra -Wshadow -o "$obj" "$file" && echo "Compilation succesful." ; exit
echo "Compilation failed."
